language: clojure
script: npx shadow-cljs release app
before_install:
  - npm install
deploy:
  provider: surge
  project: ./resources/public/
  domain: frequent-scarecrow.surge.sh
  skip_cleanup: true
